FROM docker:dind

RUN apk add --update --no-cache bash make python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip
RUN pip3 install --no-cache-dir docker-compose awscli 

